### PR TITLE
Update clang format

### PR DESCRIPTION
**Pull request by 2bndy5**
satisfy nRF24/.github#9

### CODE REVIEW

**Comment by 2bndy5** [comment]
Builds on STM32 blue pill are failing:
```
Compiling .pio/build/bluepill_f103c8/lib75e/RF24Network/RF24Network.cpp.o
In file included from /home/runner/.platformio/packages/framework-arduinoststm32/cores/arduino/wiring.h:38:
/home/runner/.platformio/packages/framework-arduinoststm32/cores/arduino/wiring_time.h: In function 'int _gettimeofday(timeval*, void*)':
/home/runner/.platformio/packages/framework-arduinoststm32/cores/arduino/wiring_time.h:106:16: error: 'getCurrentMillis' was not declared in this scope
  106 |   tv->tv_sec = getCurrentMillis() / 1000;
      |                ^~~~~~~~~~~~~~~~
/home/runner/.platformio/packages/framework-arduinoststm32/cores/arduino/wiring_time.h:107:17: error: 'getCurrentMicros' was not declared in this scope
  107 |   tv->tv_usec = getCurrentMicros() - (tv->tv_sec * 1000000);  // get remaining microseconds
      |                 ^~~~~~~~~~~~~~~~
*** [.pio/build/bluepill_f103c8/src/InteractiveServer_Mesh.ino.cpp.o] Error 1
```

I think this is related to the file name conflict about the core's clock.h and this lib's clock_arch.h, but I'm guessing it may be more specific to the header guards used:

In [cores/arduino/stm32/clock.h](https://github.com/stm32duino/Arduino_Core_STM32/blob/main/cores/arduino/stm32/clock.h) (where [`getCurrentMillis()`](https://github.com/stm32duino/Arduino_Core_STM32/blob/0ca1f4ca3d5936cf10855d2cde37e44735425edf/cores/arduino/stm32/clock.h#L38) is declared):
```c
#ifndef __CLOCK_H
#define __CLOCK_H
```
which is similar to this lib's clock_arch.h
https://github.com/nRF24/RF24Ethernet/blob/5996e137842efb52832d8a2952319198f92163b1/clock-arch.h#L21-L22

I don't know if the compiler used is doing other stuff to the header guards though. Seems like the `_` and case sensitivity should be enough to distinguish the 2 differently named files... 🤷🏼‍♂️

**Comment by 2bndy5** [comment]
Damn. That header guard thing was my best guess. I have no idea why `getCurrentMicros()` is undefined on the stm32 blue pill.

**Comment by TMRh20** [comment]
Hmm, seems to compile in the Arduino IDE, not sure if I have the right board selected tho, not finding a Blue Pill specific option but using Generic STM32F1 and other cores works fine.

**Comment by TMRh20** [comment]
Same exact error in platformio tho

**Comment by 2bndy5** [comment]
blue pill is the surname for a generic STM32F103C8

**Comment by 2bndy5** [comment]
> To the best of my knowledge, I have to use PIO in CI because there is no apparent way to install stm32duino without using the graphic installer (instead of a CLI installer). PIO allows me to avoid that hurdle because the CI runner cannot run apps with a GUI.

This is incorrect. I can use a json to install stm32duino like all other cores. I don't know how I missed this; json has been available since 2018 (v1.2.0).

I'll try and switch this in CI to arduino instead of PIO.

PS: You can select different variations of the blue pill under the tools -> "board part number" menu in Arduino IDE (after selecting generic STM32F1 board).

**Comment by 2bndy5** [comment]
CI passes now (including blue pill using Arduino). All other source changes just look like a block got indented.

**Review by TMRh20 — APPROVED** [review]

**Comment by 2bndy5** [comment]
I moved blue pill build back to PIO CI, and it works fine with the new changes from #42.

I still don't know why it worked with the Arduino CLI and not with PIO before #42, but I'm keeping the blue pill build in PIO CI just to be sure in the future.

**Pull request merged**
