### PR TITLE
Fix for #28

### LINKED ISSUE #28: Conflicting header inclusion timer
Hi, 
Thanks for the awesome library.

Currently compiling the **RF24Ethernet** for **BluePill** in **PlatformIO** cause **conflicting inclusion**.
Both stm32duino & RF24Ethernet have **timer.h**. Since Arduino IDE & PlatformIO have different inclusion order, Compiling the library in PlatformIO project cause error. 
Already the only known workaround is to fork the library, fix the file names and use the forked library in PlatformIO project.

Thanks

### PR DESCRIPTION
**Pull request by TMRh20**
Rename timer.h and timer.c

Closes #28

### CODE REVIEW

**Comment by 2bndy5** [comment]
With this fix, we should now be able to add the boards in question to the PlatformIO CI workflow (which should also validate this PR's intentions).

**Review by 2bndy5 — APPROVED** [review]
validated via PIO CI

**Comment by 2bndy5** [comment]
@TMRh20 If you're thinking of a release crusade, there's a doc change that I'd like to push in RF24 (about using cmake) beforehand.

**Comment by TMRh20** [comment]
Soon. I’m troubleshooting an issue with the interactive server example where it responds to ping but not http requests after like 17 days or more. I have a guess as to a fix but not much more. So I’m trying to fix it before the next release.

**Comment by 2bndy5** [comment]
> Soon. I’m troubleshooting an issue with the interactive server example where it responds to ping but not http requests after like 17 days or more. I have a guess as to a fix but not much more. So I’m trying to fix it before the next release.

Could it have something to do with using size_t? Here's a snippet from cppreference.com

>std::size_t is commonly used for array indexing and loop counting. Programs that use other types, such as unsigned int, for array indexing may fail on, e.g. 64-bit systems when the index exceeds [UINT_MAX](https://en.cppreference.com/w/cpp/types/climits) or if it relies on 32-bit modular arithmetic.

**Comment by TMRh20** [comment]
I dunno, I have a hunch it has to do with the UIP_TIMER_DIVISOR being set to high, but that's just a guess. I'll have to see about this size_t thing as well.

**Comment by TMRh20** [comment]
Well the timer divisor thing did nothing. I'm now trying it with the while() loop in the sketch changed to an if. Can't see where else it would loop like that... I really want to get this bug fixed before the next release, so I have three nodes running the modified sketch, and if they all stay online for 20+ days then its a win. If not, we can do a release anyway...

**Comment by 2bndy5** [comment]
Wouldn't hurt to have a thread for this problem to track it properly.

**Pull request merged**
